#spring:
#  application:
#    name: file-service
#  config:
#    import: "optional:configserver:http://172.23.0.3:8888"
#  cloud:
#    config:
#      name: file-service,common-setting
#
#  datasource:
#    url: jdbc:postgresql://172.16.28.217:5433/filerepo
#    username: "ndxservice"
#    password: "ndxpro123@"
#  jpa:
#    hibernate:
#      ddl-auto: update
#      generate-ddl: true
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
#        dialect: org.hibernate.dialect.PostgreSQLDialect